"""CLI entry point wiring together Phase 1 (deterministic core) and Phase 2
(tool-backed analyzers) of the compliance-review pipeline.

This intentionally does NOT perform the semantic/judgment checks the LLM
subject-reviewer normally does (architecture quality, naming, spec-drift,
etc.) -- those checks are written out as `N/A` with a
"requires semantic review (Phase 3, not implemented)" reason so scoring
never penalizes what wasn't evaluated. See docs/compliance-reviewer/README.md
for how this fits alongside the agent-based `compliance-reviewer` flow.

Usage:
    python -m compliance_review <target-path> [--run-vuln-scanners]
        [--transitions-root transitions] [--reports-dir docs/reports]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from .aggregate import aggregate_run
from .analyzers import run_all
from .inventory import ALL_SUBJECTS, build_inventory
from .report import build_context, render_report
from .schemas import CheckResult, Finding, TransitionHeader
from .state import (
    RunPaths,
    StateFile,
    compute_inputs_hash,
    list_resumable_runs,
    make_run_id,
    now_iso,
)
from .status import format_status_line

REPORT_DISCLAIMER = (
    "> **Note:** this report was generated by the Python `compliance_review` CLI "
    "(Phase 1 deterministic core + Phase 2 tool-backed analyzers only). Checks that "
    "require reading code semantically (architecture quality, naming, spec-vs-implementation "
    "drift, etc.) are recorded as `N/A — requires semantic review (Phase 3, not implemented)` "
    "and excluded from scoring, rather than guessed at. For a full review, run the "
    "`compliance-reviewer` agent instead, or once Phase 3 exists.\n\n"
)


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def _full_results(check_results: list[CheckResult]) -> list[dict[str, Any]]:
    by_subject: dict[str, list[dict[str, Any]]] = {}
    for cr in check_results:
        by_subject.setdefault(cr.subject, []).append({
            "checkId": cr.checkId,
            "result": cr.result,
            "evidenceOrReason": cr.reason or "",
        })
    return [{"name": subject, "checks": checks} for subject, checks in by_subject.items()]


def run(
    target_path: Path,
    transitions_root: Path,
    reports_dir: Path,
    run_vuln_scanners: bool,
    run_id: str | None = None,
) -> Path:
    run_id = run_id or make_run_id(str(target_path))
    paths = RunPaths(transitions_root, run_id)
    paths.ensure_dirs()

    inputs_hash = compute_inputs_hash(
        str(target_path), None, ALL_SUBJECTS, "vuln-scanners" if run_vuln_scanners else "file-checks-only",
    )
    state = StateFile(
        runId=run_id, targetPath=str(target_path), subjects=ALL_SUBJECTS, inputsHash=inputs_hash,
        analyzerApproval="vuln-scanners" if run_vuln_scanners else "file-checks-only",
    )
    total_steps = 4
    step_names = ["Init", "Inventory", "Analyzers", "Aggregate + Report"]

    def status(i: int, name: str, counts: dict[str, int], report_path: str | None = None) -> None:
        next_name = step_names[i] if i < len(step_names) else "done"
        remaining = step_names[i + 1:] if report_path is None else []
        print(format_status_line(i, total_steps, name, next_name, remaining, counts, report_path))

    # Step 00 - init
    started_at = now_iso()
    _write_json(paths.step_path("00-init"), TransitionHeader(
        runId=run_id, stepId="00-init", targetPath=str(target_path), status="completed",
        startedAt=started_at, completedAt=now_iso(), inputsHash=inputs_hash,
    ).to_dict())
    state.steps["00-init"] = "completed"
    state.save(paths.state_path())
    status(1, "Init", {"Error": 0, "Warning": 0, "Information": 0})

    # Step 01 - inventory
    inventory = build_inventory(str(target_path))
    _write_json(paths.step_path("01-inventory"), {
        **TransitionHeader(
            runId=run_id, stepId="01-inventory", targetPath=str(target_path), status="completed",
            startedAt=now_iso(), completedAt=now_iso(), inputsHash=inputs_hash,
        ).to_dict(),
        **inventory.to_dict(),
    })
    state.steps["01-inventory"] = "completed"
    state.save(paths.state_path())
    status(2, "Inventory", {"Error": 0, "Warning": 0, "Information": 0})

    # Step 02 - analyzers (Phase 2)
    analyzer_checks = run_all(target_path, run_vuln_scanners=run_vuln_scanners)
    check_results: list[CheckResult] = []
    findings: list[Finding] = []
    finding_seq: dict[str, int] = {}
    for ac in analyzer_checks:
        finding_id = None
        if ac.passed is False:
            finding_seq[ac.checkId] = finding_seq.get(ac.checkId, 0) + 1
            finding_id = f"{ac.checkId}#{finding_seq[ac.checkId]}"
        check_results.append(ac.to_check_result(finding_id))
        finding = ac.to_finding(finding_id) if finding_id else None
        if finding:
            findings.append(finding)

    _write_json(paths.step_path("02-analyzers"), {
        **TransitionHeader(
            runId=run_id, stepId="02-analyzers", targetPath=str(target_path), status="completed",
            startedAt=now_iso(), completedAt=now_iso(), inputsHash=inputs_hash,
        ).to_dict(),
        "checkResults": [c.to_dict() for c in check_results],
        "findings": [f.to_dict() for f in findings],
    })
    state.steps["02-analyzers"] = "completed"
    state.save(paths.state_path())
    status(3, "Analyzers", {
        "Error": sum(1 for f in findings if f.severity == "Error"),
        "Warning": sum(1 for f in findings if f.severity == "Warning"),
        "Information": sum(1 for f in findings if f.severity == "Information"),
    })

    # Step 90/99 - aggregate + report
    aggregate = aggregate_run(check_results, findings, strengths=[])
    _write_json(paths.step_path("90-aggregate"), {
        **TransitionHeader(
            runId=run_id, stepId="90-aggregate", targetPath=str(target_path), status="completed",
            startedAt=now_iso(), completedAt=now_iso(), inputsHash=inputs_hash,
        ).to_dict(),
        **aggregate.to_dict(),
    })
    state.steps["90-aggregate"] = "completed"

    context = build_context(
        aggregate,
        target_name=target_path.name,
        generated_at=now_iso(),
        run_id=run_id,
        target_path=str(target_path),
        target_git_head=None,
        started_at=started_at,
        completed_at=now_iso(),
        skipped_subjects=inventory.skippedSubjects,
        urls_fetched=[],
        link_approvals={},
        full_results=_full_results(check_results),
    )
    report_text = REPORT_DISCLAIMER + render_report(context)
    reports_dir.mkdir(parents=True, exist_ok=True)
    report_path = reports_dir / f"{target_path.name}-compliance-review-python-{run_id}.md"
    report_path.write_text(report_text, encoding="utf-8")

    _write_json(paths.step_path("99-report"), {
        **TransitionHeader(
            runId=run_id, stepId="99-report", targetPath=str(target_path), status="completed",
            startedAt=now_iso(), completedAt=now_iso(), inputsHash=inputs_hash,
        ).to_dict(),
        "reportPath": str(report_path),
    })
    state.steps["99-report"] = "completed"
    state.status = "completed"
    state.reportPath = str(report_path)
    state.save(paths.state_path())
    status(4, "Aggregate + Report", aggregate.severityCounts, report_path=str(report_path))

    return report_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="compliance_review", description=__doc__)
    parser.add_argument("target_path", nargs="?", help="Path to the repo to review (read-only)")
    parser.add_argument("--run-vuln-scanners", action="store_true",
                         help="Also shell out to dotnet/npm/pip-audit to check for known-vulnerable dependencies")
    parser.add_argument("--transitions-root", default="transitions", type=Path)
    parser.add_argument("--reports-dir", default="docs/reports", type=Path)
    parser.add_argument("--run-id", default=None)
    parser.add_argument("--list-resumable", action="store_true",
                         help="List runs under --transitions-root whose state.json isn't completed, then exit")
    args = parser.parse_args(argv)

    if args.list_resumable:
        for run_id in list_resumable_runs(args.transitions_root):
            print(run_id)
        return 0

    if not args.target_path:
        parser.error("target_path is required unless --list-resumable is given")

    target_path = Path(args.target_path).resolve()
    if not target_path.is_dir():
        parser.error(f"target_path does not exist or is not a directory: {target_path}")

    report_path = run(
        target_path=target_path,
        transitions_root=args.transitions_root,
        reports_dir=args.reports_dir,
        run_vuln_scanners=args.run_vuln_scanners,
        run_id=args.run_id,
    )
    print(f"\nReport written to {report_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
